---
title: "Beasts & Bytes"
subtitle: "Data Science Applications in Agriculture"
---

# Course description

This course offers an undergraduate experience in challenge-based learning, where students tackle data-driven problems within the agricultural sector. If you have never heard about it, check out this [Solar Car Challenge](https://www.solarcarchallenge.org/challenge/) that you might recogize. Working in collaborative teams, students will engage directly with farmers and industry stakeholders to understand a real-world challenge and develop an innovative, data-driven solutions.

Throughout the course, students will learn to utilize a range of digital tools essential for modern data science. Key topics covered include data governance, ensuring data privacy, effective data collection methods, efficient data storage solutions, data processing techniques, and advanced data visualization. Students will also delve into data modeling and the art of presenting data in a clear and impactful manner.

Project management is a core component of the course, with students learning to manage projects effectively, adhere to deadlines, and deliver results in a timely manner. The course emphasizes the importance of teamwork, communication, and collaboration, preparing students to work in diverse and dynamic environments.

By the end of the course, students will have gained practical experience and developed a skill set that includes problem-solving, critical thinking, and the ability to create sustainable solutions for the agricultural industry. This course is ideal for students interested in applying data science to real-world problems and making a tangible impact in the field of agriculture.

# Objectives

1.  Understand the fundamentals of data science and digital agriculture including the interdisciplenary challenges.

2.  Explore the various data science technologies, precision farming techniques and digital tools used in modern agriculture.

3.  Conduct data collection, visualization, analysis, and interpretation within the context of digital agriculture.

4.  Acquire practical skills through hands-on programming activities.

5.  Explore the applications of machine learning and artificial intelligence in agriculture.

6.  Recognize the significance of and utilize data privacy and security in digital agriculture.

# Outline

See [this link](https://bovi-analytics.github.io/BeastsAndBytes/course-overview.html) for details on course outline. As this course is the first of its kind, expect updates to happen to this course outline during the fall semester of 2024.

# Format

This course will consist of a combination of lectures, hands-on practical sessions, a case study, group discussions, and guest lectures from industry experts. Students will also have the opportunity to work on a real-world project related to digital agriculture.

## General week format

|     | Monday  | Tuesday | Wednesday         | Thursday                      | Friday                               |
|-----|---------|---------|-------------------|-------------------------------|--------------------------------------|
| am  |         |         |                   |                               | Bi-weekly project management meeting |
| pm  | Lecture |         | Weekly coding lab | Project (incl. 3 field trips) |                                      |
|     |         |         |                   |                               |                                      |

## Lectures

The goal of the lectures is to have them as interactive as possible (which requires your attendance and participation). My role as instructor is to introduce you new tools and techniques, but it is up to you to take them and make use of them.

## Labs

One the things you will definitely learn in this course will involve writing code, and coding is a skill that is best learned by doing. Therefore, as much as possible, you will need to finish a weekly coding assignment. Every week a new assignment will be opened for each of you on the online coding platform [Dodona](https://www.dodona.be/). There is a strict deadline at Friday evening 17:00 to finish the assignment, individually. The number of successfully finished assignments at the end of the course is part of your individual grading (see below).

## Project

Throughout the course, you will engage in a group project that involves solving a real-world, data-intensive problem in agriculture. Working in teams, you will collaborate with farmers and stakeholders to identify the exact problem. Your task will be to develop a data-driven solution using digital tools and techniques learned during the course.

### **Differrent project phases we will tackle together**

1.  **Problem Identification:** We will begin by meeting with the farmer (and stakeholders) to understand the problem and their need. This will include conducting an initial research to define the problem clearly.

2.  **Data Collection:** You will gather relevant data from various sources, ensuring adherence to data privacy and governance standards.

3.  **Data Analysis and Visualization:** You will analyze the collected data (using techniques covered in the labs) to describe insights and trends, including the use of visualization tools to present your findings effectively.

4.  **Solution Development:** Next, different statistical, or machine learning techniques will be explored to develop a practical solution. This phase will involve hands-on programming.

5.  **Implementation Plan:** Create a detailed plan for implementing the proposed solution.

6.  **Presentation:** You will prepare and present your project to the farmer, including your methodology, findings, and proposed solution.

### Weekly project meetings

We will hold weekly project meetings during which we will discuss the groups overal progress, address any challenges, and provide guidance. These meetings are an opportunity for you to share updates, receive feedback, and collaborate with your peers and instructors. Your active participation is crucial to ensure that we stay on track and achieve our project goals.

# Textbook

While there is no official textbook for the course, we will be assigning readings from the following some of the following textbooks.

-   [R for Data Science](https://r4ds.had.co.nz/) by Garret Grolemund and Hadley Wickham.

-   Weekly assignments from the [Introduction to Data Science](https://rafalab.dfci.harvard.edu/dsbook-part-1/) handbook by Rafael Irizarry.

-   Others related to the project will be proposed during the

# Website

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website at [bovi-analytics.github.io/BeastsAndBytes/](https://bovi-analytics.github.io/BeastsAndBytes/).

Although I will try to avoid last minute changes to the schedule this might happen given this challenged based learning course. I will send course announcements via email.

# Assessment & grading

Assessment methods will include individual coding assignments and a group project including presentations and group report.

## Group assessment

| Component graded                                                                           | Weight | Remark                                                                                                                    |
|--------------------------------------------------------------------------------------------|--------|---------------------------------------------------------------------------------------------------------------------------|
| Use of appropriate naming conventions throughout project (subgroups)                       | 20%    | Failure to use any naming convention in the project will result in failing the entire group project.                      |
| FAIR principle compliance in reporting, documentation of data and coding through notebooks | 20%    | Failure to implement any of the FAIR principles will result in failing the entire group project.                          |
| Project presentation                                                                       | 30%    | We will discuss within the group how to assess each individuals contribution (as some people maybe even will not present) |
| Project report (entire group)                                                              | 30%    |                                                                                                                           |

## Individual assessment

**It is very important to read this part as your individual assessments will be influencing your indiviual grading.**

At the end of the course you will be evaluated on the % of weekly assignments you have coded correctly in the Dodona framework (which is very easy to use). That % will be multiplied with the overal group project grade, resulting in your final individual grade.

For example:

-   Group project was graded at 95%

-   Student A successfully finished 75% of the coding assignments within each deadline. As a result student A gets 95%\*75% = 71% as the final individual grade.

-   Student B successfully finished 100% of the coding assignments within each deadline. As a result student B gets 95%\*100% as the final individual grade.

Finishing each of the assignments within each deadline is not that difficult. You "just" need to devote the time to it. I have used this method a lot during my courses. It is not to annoy students, but to make sure the entire group keeps progressing on the programming skills during the project. You will thank me for that at a certain moment. For full transparency, I learned to code Python using a similar approach. Once I understood why this was done, I started appreciating this method as one of the most inspiring learning methods I had ever seen.

# Policies

## Inclusive community

I grew up in a family in which values as diversity, equity and inclusion were at the core of our everyday life. My parents were both involved taking care of people struggling with equity and inclusion, and as a result these values are deeply embedded in my character.

I aim to ensure that students from all diverse backgrounds and perspectives are well-served by this course. I strive to address students’ learning needs both in and out of class, and to view the diversity that students bring as a resource, strength, and benefit. My goal is to present materials and activities that respect diversity and align with Cornell University’s core values. Sometimes it might fade during busy times, don't be afraid to recall someone, we're all humans after all. "*Your suggestions are truely encouraged and appreciated"*. Please let me know how I can improve the course’s effectiveness for you personally, or for other students or student groups.

Additionally, I aim to foster a learning environment that embraces a diversity of thoughts, perspectives, and experiences, and respects your identities. If your experiences outside of class are affecting your performance, please feel free to talk with me. Alternatively, your academic dean is a great resource if you prefer to speak with someone outside the course.

## Academic Integrity

Absolute integrity is expected of every Cornell student in all academic undertakings. Integrity entails a firm adherence to a set of values, and the values most essential to an academic community are grounded on the concept of honesty with respect to the intellectual efforts of oneself and others, and free and open inquiry and discussion in the classroom. Academic integrity is expected not only in formal coursework situations, but in all University relationships and interactions connected to the educational process, including the use of University resources. While both students and faculty of Cornell assume the responsibility of maintaining and furthering these values, this document is concerned specifically with the conduct of students.

A Cornell student’s submission of work for academic credit indicates that the work is the student’s own. All outside assistance should be acknowledged, and the student’s academic position truthfully reported at all times. In addition, Cornell students have a right to expect academic integrity from each of their peers.

This a [guideline for students](https://deanoffaculty.cornell.edu/faculty-and-academic-affairs/academic-integrity/guidelines-for-students/) offered through the [Office of the Dean of Faculty](https://deanoffaculty.cornell.edu/)

# 
