---
title: "Beasts & Bytes"
tbl-colwidths: [5,5,15,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the course. Note that this schedule will be updated as the course progresses, with all changes documented here.

::: column-screen-inset-right
|          Week           | Date             | Topic | Teachers |                                  Prepare                                   |                             Slides                              | Code'n Practice |                                 Assignment                                 |                             Project                              |
|:------:|:---------------|------------------------|---------------|:------:|:------:|:------:|:------:|:------:|
| [1](/weeks/week-1.html) | Mon, 9:00-9:45   |       |          |                                                                            |            [🖥️](slides/lec-1.html "Lecture slides")             |                 |                                                                            |                                                                  |
|                         | Wed, 13:00-16:00 |       |          |     [📖](weeks/week-1.html#introduction-to-statistical-programming-wc)     |          [🖥️](/computing-access.html "Lecture slides")          |                 |                                                                            |                                                                  |
|                         | Mon, 11:00-11h45 |       |          |                                                                            | [🖥️](https://prezi.com/view/K5uOZ9e0ilLYWFkgE27W/ "Lab slides") |                 |                                                                            |                                                                  |
| [2](/weeks/week-2.html) | Mon, 11:00-11h45 |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Mon, 13:15-15:00 |       |          |                                                                            |                                                                 |                 |                                                                            | [📂](https://drive.google.com/drive/folders/0AP9RxLUFwHObUk9PVA) |
|                         | Mon, 15:15-17:00 |       |          |  [📖](weeks/week-1.html#a-guideline-to-reproducible-fair-data-science-ic)  |                                                                 |                 |                                                                            |                                                                  |
|                         | Tue, 13:00-17:00 |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Wed, 13:15-17:00 |       |          |       [📖](https://dodona.be/en/courses/2982/#series-32095-prologue)       |                                                                 |       💻        |                                                                            |                                                                  |
|                         | Th, 9:00-12:00   |       |          |           [📖](weeks/week-1.html#challenges-of-data-privacy-ic)            |      [🖥️](https://ulearning.uu.nl/course/view.php?id=838)       |                 |                                                                            |                                                                  |
|                         | Fr, 11:00-12:45  |       |          |                                                                            |                                                                 |                 |                                                                            | [📂](https://drive.google.com/drive/folders/0AP9RxLUFwHObUk9PVA) |
|                         | Fr, 17:00        |       |          |                                                                            |                                                                 |                 |      [📋](https://dodona.be/en/courses/2982/#series-32098-2-r-basics)      |                                                                  |
| [2](/weeks/week-2.html) | Mon, 11:00-12:45 |       |          |      [📖](weeks/week-2.html#modelling-biological-linear-processes-wc)      |                                                                 |                 |                                                                            |                                                                  |
|                         | Tue, 13:15-17:00 |       |          |      [📖](weeks/week-2.html#modelling-biological-linear-processes-wc)      |       [🖥️](https://prezi.com/view/5qya8mcjAuEuXwnASN2Y/)        |                 |                                                                            |                                                                  |
|                         | Wed, 13:15-17:00 |       |          | [📖](https://dodona.be/en/courses/2982/#series-32099-3-programming-basics) |                                                                 |                 |                                                                            |                                                                  |
|                         | Fr, 11:00-12:45  |       |          |                                                                            |                                                                 |                 |                                                                            | [📂](https://drive.google.com/drive/folders/0AP9RxLUFwHObUk9PVA) |
|                         | Fr, 17:00        |       |          |                                                                            |                                                                 |                 | [📋](https://dodona.be/en/courses/2982/#series-32099-3-programming-basics) |                                                                  |
| [3](/weeks/week-3.html) |                  |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Wed, 13:15-17:00 |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Th, 11:00-12:45  |       |          |                                                                            |                                                                 |                 |                                                                            | [📂](https://drive.google.com/drive/folders/0AP9RxLUFwHObUk9PVA) |
|                         | Fr, 17:00        |       |          |                                                                            |                                                                 |                 |   [📋](https://dodona.be/en/courses/2982/#series-32100-4-the-tidyverse)    |                                                                  |
| [4](/weeks/week-4.html) |                  |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Wed, 13:15-17:00 |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Fr, 11:00-12:45  |       |          |                                                                            |                                                                 |                 |                                                                            | [📂](https://drive.google.com/drive/folders/0AP9RxLUFwHObUk9PVA) |
|                         | Fr, 17:00        |       |          |                                                                            |                                                                 |                 |   [📋](https://dodona.be/en/courses/2982/#series-32101-5-importing-data)   |                                                                  |
| [5](/weeks/week-5.html) |                  |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Tue, 13:00-17:00 |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Fr, 11:00-12:45  |       |          |                                                                            |                                                                 |                 |                                                                            | [📂](https://drive.google.com/drive/folders/0AP9RxLUFwHObUk9PVA) |
|                         | Fr, 13:15-15:00  |       |          |                                                                            |                                                                 |                 |                                                                            |                                                                  |
|                         | Fr, 17:00        |       |          |                                                                            |                                                                 |                 |                                     📋                                     |                                                                  |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|-----|-----|-----|:---:|:---:|:---:|:---------------------------:|:---:|:---:|:---:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
