---
title: "Python Code Examples"
format: html
editor: visual
---

# String Slicing
s = 'Scooby is a good dog.'
s[0:2]           # Sc
s[1:4]           # coo
s[:4]            # Scoo
s[12:]           # good dog.

# Concatenation
x = 'Scooby'
y = 'Chenille'
z = 3
x + y            # ScoobyChenille
x + ' ' + y      # Scooby Chenille
x + str(z)       # Scooby3

# String methods
s = 'Scooby is a good dog.'
s.find('o')      # 2
s.index('o')     # 2
s.find('x')      # -1
s.index('x')     # error
s.index('o',4)   # 13

s = 'ant, bat, cow'
s.split()        # ['ant,', 'bat,', 'cow'] (splits on spaces by default)
s.split(',')     # ['ant', ' bat', ' cow']

s = '  Go Big Red    '
s.strip()        # Go Big Red

s = 'Scooby barks'
s.upper()        # SCOOBY BARKS
s.lower()        # scooby barks

s = '123'
s.isalpha()      # False
s.isnumeric()    # True
s = '-123'
s.isnumeric()    # False

# Conditionals
x = 1
#x = '1'                # what would this do if uncommented?
if x == 0:
    print('x is 0')
elif x == 1:
    print('x is 1')
else:
    print('x is not 0 or 1')

# and, or
x = 2
if x == 2 or x == 3:
    print('or')
elif x == 2 and x == 3:
    print('and')
#if x == 2 or 3:        # nope, must have complete expressions

# Containers - Lists
l = []                  # blank list
l = list()              # same
l = [2, 4, 6]           # populated list
l = [2, 'bat', 3.14]    # mixed contents
l.append(7)             # adds the int 7 to the end of the list
l.append('dog')         # adds the string 'dog' to the end of the list

# Slicing lists is a lot like slicing strings!
l = [3.1, 6.2, 7.7, 8.8]
# Addressing one element returns that element
l[2]             # 7.7
# Slicing the list creates a new list
l[2:]            # [7.7, 8.8]

# in / not in
if 4 in l:
    print('Found 4')
if 5 not in l:
    print('No 5')

# Loops
critters = ['ant', 'bat', 'cow']
for x in critters:
    print(x)

# Containers - Dictionaries
key = 3
value = 'cow'
d = {}                  # blank dictionary
d = dict()              # same
d[key] = value          # adding values to a dict
if key in d:
    print('Found key ' + str(key))

# Containers - Tuples
t = ()                # blank tuple
t = tuple()           # same
t = (3,)              # single element tuple
nt = (3)              # not a tuple
t = (3,4,5)           # tuple
x = 3
y = 'cow'
t = (x,y)             # (3, 'cow')
print('t is a ' + str(type(t)) + ' and equals ' + str(t))

# Containers - Sets
s = set()             # blank set
s = {2,3}             # populated set
s.add(3)
s.add(7)
s.add(3)
print(s)              # {2, 3, 7}

# opening text files - reading
myFile = 'test.txt'
print('Looping through a file')
with open(myFile,'r') as f:
    for line in f:
        print(line.strip())

print('One line at a time')
with open(myFile,'r') as f:
    # cursor starts at beginning of file
    x = f.readline()
    print(x)
    # cursor now at second line
    x = f.readline()
    print(x)

# Mixed, reading a single line then looping through the rest
myFile = 'test.txt'
with open(myFile,'r') as f:
    line = f.readline() # line 1
    # do something with first line, here I'll just print it
    print(line)
    for line in f:      # lines 2-end
        # do something with each subsequent line, here I'll just print them
        print(line)

# opening text files - writing
with open('test2.txt','w') as f:
    f.write('Scooby likes to chase rabbits.')

# Functions
def doubleMe(x):
    return (x * 2)
x = 5
print(doubleMe(x))
y = 6
print(doubleMe(y))

def varsAreLocal(x):
    x = 0
x = 3
varsAreLocal(x)
print(x)

# dates
import datetime
now = datetime.datetime.now()
myDate = datetime.datetime.strftime(now, '%Y-%m-%d')
myDate2 = datetime.datetime.strftime(now, '%m/%d/%Y')
print(myDate)

# scanning a folder
import pathlib # newer way to do paths
# . - Starting at current working dir
# \\ - backslash (doubled since it's a switch)
# cs1133 - assumes a folder \cs1133 under current folder
path = pathlib.Path('.\\cs1133')
# path = pathlib.Path('\\\\networkshare\\folder1\\folder2')
for file in path.glob('*.py'):
    print(file.name)

Can you think on another way to get this new_df2?
